### ISSUE TITLE
Discuss future direction

### ISSUE THREAD

**Issue by david-sawatzke** [sajattack/ws2812-rs#1]
From https://github.com/atsamd-rs/atsamd/issues/32.

I'd prefer to have the high-level library and the implementations as separate crates, because there may be better implementations. On AVR, your bit delay stuff is different than on arms, where some people are using gpio pins and dmas, so you can't really do it all (I think).

**Comment by david-sawatzke** [comment]
I'd also prefer an iterator based approach, so you can do multiple transformation and effects, without having to use much ram and/or doing destructive transformations. 

I'd also not keep it ws2812 specific, because there are many (for example the apa ones) that are similar but not the same

**Comment by sajattack** [comment]
I think adafruit keeps APA102 and WS2812 separate but I could be wrong. I like your ideas of separate backend crates and iterators.

**Comment by david-sawatzke** [comment]
Yeah, but the API for the driver is pretty much the same. The only difference is that the color bytes are in a different order and a seperate brightness PWM is implemented, but that one isn't recommended by adafruit because the frequency is really low.

We could have a programmable-led-api crate which is used by the backends, which defines the interface of the iterator of the trait, a separate effects crate which implements various iterators, that can consume each other and so on, and last but not least the various backends.

We should also make sure to always implement `size_hint` (https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint), so that it can efficiently work on raspberry pis and the like

**Comment by david-sawatzke** [comment]
I'd ask around on irc

**Comment by sajattack** [comment]
Maybe smart-led is a better name. Don't want it to be too long.

**Comment by david-sawatzke** [comment]
Probably a good idea. Maybe under an organization or something? 

This is my current plan for the crate structure: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0cb67a7076b9e00d69c7b6e00a1727ac

**Comment by sajattack** [comment]
I would probably want to have the crate with the Trait to also be the crate with the high-level api.

**Comment by david-sawatzke** [comment]
I'd export it for end users in the high-level api, but leave it separately for implementers. I think it's more clear where responsibilities and there'll (probably) be less api breakage because of updates

**Comment by sajattack** [comment]
Ok, that makes sense.

**Comment by sajattack** [comment]
Note to future readers: We have moved to https://github.com/smart-leds-rs The equivalent of this repo is now https://github.com/smart-leds-rs/ws2812-nop-samd21
